CREATE TABLE MEAL (
  NAME VARCHAR(255),
  PRICE DOUBLE, 
  CALORIES INT
);
CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Eggs', false, true, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Bread', false, true, true, false);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Beef Patty', false, false, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Lettuce', false, true, true, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Yoghurt', true, true, false, true);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);

CREATE TABLE CHEAP_MEALS AS SELECT * FROM MEAL WHERE PRICE < 15.0;
SELECT * FROM CHEAP_MEALS;
CREATE TABLE VEGAN_INGREDIENT AS SELECT * FROM INGREDIENT WHERE FALSE;
INSERT INTO VEGAN_INGREDIENT SELECT * FROM INGREDIENT WHERE VEGAN;
SELECT * FROM VEGAN_INGREDIENT;
CREATE VIEW EXPENSIVE_MEALS AS SELECT * FROM MEAL WHERE PRICE > 15.0;
SELECT * FROM EXPENSIVE_MEALS;
CREATE TABLE LACTOSE_FREE_INGREDIENT AS SELECT * FROM INGREDIENT WHERE !CONTAINS_LACTOSE;
SELECT * FROM LACTOSE_FREE_INGREDIENT;
CREATE VIEW HIGH_CALORIES_MEALS AS SELECT * FROM MEAL WHERE CALORIES > 650;
SELECT * FROM HIGH_CALORIES_MEALS;