CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Eggs', 10.20, false, true, false, true);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Bread', 15.2, false, true, true, false);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Beef Patty', 20.5, false, false, false, true);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Lettuce', 5.3, false, true, true, true);

INSERT INTO INGREDIENT (NAME, PRICE, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Yoghurt', 7.0, true, true, false, true);

SELECT NAME FROM INGREDIENT;
SELECT NAME, PRICE FROM INGREDIENT;
SELECT * FROM INGREDIENT ORDER BY NAME;
SELECT * FROM INGREDIENT ORDER BY GLUTEN_FREE;