CREATE TABLE INGREDIENT (
  NAME VARCHAR(255),
  CONTAINS_LACTOSE BOOLEAN,
  VEGETARIAN BOOLEAN,
  VEGAN BOOLEAN,
  GLUTEN_FREE BOOLEAN
);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Eggs', false, true, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Bread', false, true, true, false);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Beef Patty', false, false, false, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Lettuce', false, true, true, true);

INSERT INTO INGREDIENT (NAME, CONTAINS_LACTOSE, VEGETARIAN, VEGAN, GLUTEN_FREE) 
VALUES ('Yoghurt', true, true, false, true);

ALTER TABLE INGREDIENT
MODIFY COLUMN NAME VARCHAR(255) NOT NULL;
ALTER TABLE INGREDIENT
MODIFY COLUMN CONTAINS_LACTOSE BOOLEAN NOT NULL;
ALTER TABLE INGREDIENT
MODIFY COLUMN VEGETARIAN BOOLEAN NOT NULL;
ALTER TABLE INGREDIENT
MODIFY COLUMN VEGAN BOOLEAN NOT NULL;
ALTER TABLE INGREDIENT
MODIFY COLUMN GLUTEN_FREE BOOLEAN NOT NULL;
ALTER TABLE INGREDIENT
ADD CONSTRAINT UNIQUE (NAME);



